name: task-manager-app
region: nyc
services:
  - name: web
    source_dir: /
    github:
      repo: task-manager-test2-app-autodev
      branch: main
      deploy_on_push: false
    run_command: gunicorn --bind 0.0.0.0:$PORT --workers 3 --worker-class gevent --timeout 120 app:app
    environment_slug: python
    instance_count: 1
    instance_size_slug: professional-xs
    http_port: 8080
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      success_threshold: 1
      failure_threshold: 3
      timeout_seconds: 5
    routes:
      - path: /
    envs:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
      - key: CORS_ALLOWED_ORIGINS
        value: ${CORS_ALLOWED_ORIGINS}
      - key: MAIL_SERVER
        value: ${MAIL_SERVER}
      - key: MAIL_PORT
        value: ${MAIL_PORT}
      - key: MAIL_USERNAME
        value: ${MAIL_USERNAME}
      - key: MAIL_PASSWORD
        value: ${MAIL_PASSWORD}
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: REDIS_PASSWORD
        value: ${REDIS_PASSWORD}
      - key: ENVIRONMENT
        value: ${ENVIRONMENT}
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_CONTENT_LENGTH
        value: "16777216"
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: SESSION_COOKIE_HTTPONLY
        value: "true"
      - key: SESSION_COOKIE_SAMESITE
        value: "Lax"
      - key: WTF_CSRF_TIME_LIMIT
        value: "3600"
      - key: SQLALCHEMY_ENGINE_OPTIONS
        value: '{"pool_pre_ping": true, "pool_recycle": 300}'

databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb
    num_nodes: 1
    production: true
  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-dev-database
    num_nodes: 1
    production: false

static_sites:
  - name: static
    source_dir: app/static
    routes:
      - path: /static

workers:
  - name: websocket-worker
    source_dir: /
    github:
      repo: task-manager-test2-app-autodev
      branch: main
      deploy_on_push: false
    run_command: python -m app.websocket.server
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: ENVIRONMENT
        value: ${ENVIRONMENT}

alerts:
  - rule: CPU_UTILIZATION
    value: 80
    operator: GREATER_THAN
    window: FIVE_MINUTES
    disabled: false
  - rule: MEM_UTILIZATION
    value: 85
    operator: GREATER_THAN
    window: FIVE_MINUTES
    disabled: false
  - rule: RESTART_COUNT
    value: 5
    operator: GREATER_THAN
    window: FIVE_MINUTES
    disabled: false